[project]
name = "pycufsm"
version = "0.2.0"
authors = [{ name = "Brooks H. Smith", email = "smith120bh@gmail.com" }]
description = "Python CUFSM (Constrained and Unconstrained Finite Strip Method)"
keywords = [
    "FSM",
    "finite strip",
    "CUFSM",
    "CFS",
    "thin-walled",
    "cold-formed steel",
    "aluminium",
    "structural engineering",
    "structural analysis",
]
license = "LGPL-3.0"
classifiers = [
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.23.5",
    "scipy>=1.10.0",
]

[project.urls]
Homepage = "https://github.com/brookshsmith/pyCUFSM"
Repository = "https://github.com/brookshsmith/pyCUFSM"
Documentation = "https://pycufsm.readthedocs.io"

[project.optional-dependencies]
plot = [
    "matplotlib>=3.2"
]
jupyter = [
    "ipywidgets>=8.0.0",
    "matplotlib>=3.2"
]

[dependency-groups]
dev = [
    "numpy==2.2.6",
    "scipy==1.15.3",
    "matplotlib==3.10.7",
    "ipywidgets==8.1.8",
]
test = [
    "pylint==4.0.2",
    "mypy==1.18.2",
    "typing_extensions==4.15.0; python_version<'3.12'",
    "black[jupyter]==25.9.0",
    "pytest==8.4.2",
    "pytest-describe==3.0.0",
    "pytest-pspec==0.0.4",
    "pytest-raises==0.11",
]
docs = [
    "sphinx==9.1.0; python_version>='3.12'",
    "sphinx-autoapi==3.6.0",
    "sphinx-rtd-theme==3.1.0",
]

[build-system]
requires = [
    "poetry-core>=2.2.0",
    "setuptools>=61.0",
    "cython>=3.0",
    "numpy>=2.0.0rc1",
]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "pycufsm" }]
include = ["py.typed", "*.pyx"]

[tool.poetry.build]
script = "build_cython_ext.py"
generate-setup-file = true

[tool.pylint]
disable = [
    "too-many-locals",
    "too-many-arguments",
    "too-many-positional-arguments",
    "too-many-statements",
    "too-many-branches",
    "too-many-nested-blocks",
    "duplicate-code",
    "missing-module-docstring",
    "too-many-lines",
    "logging-fstring-interpolation",
    "using-f-string-in-unsupported-version",
]
variable-rgx = '[a-zA-Z_][a-zA-Z0-9_]{0,30}$'
argument-rgx = '[a-zA-Z_][a-zA-Z0-9_]{0,30}$'
function-rgx = '[a-zA-Z_][a-zA-Z0-9_]{2,30}$'
max-line-length = 120
py-version = [3.10, 3.11, 3.12, 3.13, 3.14]

[tool.mypy]
packages = "pycufsm"
python_version = "3.10"
strict = true
allow_any_generics = true
implicit_reexport = true
exclude = ['gui_widgets\.py']

[tool.black]
line-length = 120
target-version = ['py310', 'py311', 'py312', 'py313']
